---
- hosts: appserver
  become: yes
  vars:
    repo_url: "https://github.com/deepakbatra5/fullstack-cicd-project.git"
    app_path: "/home/ubuntu/FULLSTACK-CICD-PROJECT"

  tasks:

    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install required packages for Git & Docker & Compose
      apt:
        name:
          - git
          - docker.io
          - docker-compose
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    # --------------------------------------------------------------------
    #   CLONE / UPDATE CODE
    # --------------------------------------------------------------------

    - name: Create app directory
      file:
        path: "{{ app_path }}"
        state: directory

    - name: Clone or pull latest code
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_path }}"
        version: main
        force: yes

    # --------------------------------------------------------------------
    #   RUN DOCKER COMPOSE (APP + DB)
    # --------------------------------------------------------------------

    - name: Stop existing docker containers
      shell: docker compose down
      args:
        chdir: "{{ app_path }}"

    - name: Build and start services using docker compose
      shell: docker compose up -d --build
      args:
        chdir: "{{ app_path }}"

    - name: Show running containers
      shell: docker ps
