- hosts: appserver
  become: yes
  vars:
    repo_url: "https://github.com/deepakbatra5/fullstack-cicd-project.git"
    app_path: "/home/ubuntu/FULLSTACK-CICD-PROJECT"

  tasks:

    # ---------------------------------------------------------
    # INSTALL DOCKER IF NOT INSTALLED
    # ---------------------------------------------------------

    - name: Check if Docker is installed
      command: which docker
      register: docker_exists
      ignore_errors: yes

    - name: Install Docker using official script
      shell: curl -fsSL https://get.docker.com | sh
      when: docker_exists.rc != 0

    

    # ---------------------------------------------------------
    # CLONE / UPDATE PROJECT
    # ---------------------------------------------------------

    - name: Create app directory if missing
      file:
        path: "{{ app_path }}"
        state: directory

    - name: Clone or update repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_path }}"
        version: main
        force: yes

    # ---------------------------------------------------------
    # BUILD & RUN DOCKER COMPOSE
    # ---------------------------------------------------------

    - name: Build and start services using docker compose
      shell: docker compose up -d --build
      args:
        chdir: "{{ app_path }}"
