---
- hosts: appserver
  become: yes
  vars:
    repo_url: "https://github.com/deepakbatra5/fullstack-cicd-project.git"
    app_path: "/home/ubuntu/FULLSTACK-CICD-PROJECT"

  tasks:

    - name: Update apt packages
      apt:
        update_cache: yes

    # ---------------------------------------------------------
    # Install Latest Docker + Compose v2 (Official Script)
    # ---------------------------------------------------------
    - name: Download Docker install script
      get_url:
        url: https://get.docker.com
        dest: /tmp/get-docker.sh
        mode: '0755'

    - name: Run Docker install script
      shell: sh /tmp/get-docker.sh

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    # ---------------------------------------------------------
    # Clone Project
    # ---------------------------------------------------------
    - name: Create app directory if missing
      file:
        path: "{{ app_path }}"
        state: directory

    - name: Clone or update repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_path }}"
        version: main
        force: yes

    # ---------------------------------------------------------
    # Run docker compose
    # ---------------------------------------------------------
    - name: Stop existing docker containers
      shell: docker compose down
      args:
        chdir: "{{ app_path }}"
      ignore_errors: yes

    - name: Build & start services with docker compose
      shell: docker compose up -d --build
      args:
        chdir: "{{ app_path }}"

    - name: Show running containers
      shell: docker ps
