---
- hosts: appserver
  become: yes
  vars:
    repo_url: "https://github.com/deepakbatra5/fullstack-cicd-project.git"
    app_path: "/home/ubuntu/FULLSTACK-CICD-PROJECT"

  tasks:


    # ---------------------------------------------------------
    # CLONE / UPDATE PROJECT
    # ---------------------------------------------------------
    - name: Create app directory if missing
      file:
        path: "{{ app_path }}"
        state: directory

    - name: Clone or update repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_path }}"
        version: main
        force: yes
      

    - name: Build and start services using docker compose
      shell: docker compose up -d --build
      args:
        chdir: "{{ app_path }}"

   
